/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;


import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author AMOD_PC
 */
public class Login extends javax.swing.JFrame {

    public Connection cn;
    public PreparedStatement st;
    ResultSet rs=null;
    public Login() {
        initComponents();
        lblFrontLayer.hide();
        jTextArea1.hide();
        //secure yur acc labale
        jLabel5.hide();
        //b_a_k_e h logo hide
        jLabel6.hide();
        setBackground(new Color(0,0,0,0));
          try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/bakehouse?zeroDateTimeBehavior=convertToNull","root","");
           // JOptionPane.showMessageDialog(null, "conneted");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Not conneted");
        }
        
         //make jframe center
         Toolkit toolkit=getToolkit();
         Dimension size=toolkit.getScreenSize();
         setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
         
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        lablelBurgerPic3 = new javax.swing.JLabel();
        lblFrontLayer1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblLoginPassword1 = new javax.swing.JLabel();
        txtChangeNewPass = new javax.swing.JTextField();
        btnChangeLogin = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        lblLoginUserName2 = new javax.swing.JLabel();
        txtChangeName = new javax.swing.JTextField();
        lblLoginPassword2 = new javax.swing.JLabel();
        txtChangeConfirmPass = new javax.swing.JTextField();
        lblFrontLayer = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblLoginUserName = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnLoginChange = new javax.swing.JButton();
        lblLoginPassword = new javax.swing.JLabel();
        lblLoginUserName1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtLoginUserId = new javax.swing.JTextField();
        txtLoginUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lablelRedTexture1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\nFounded in 1960, BAKEHOUSE's is the recognized world\n       leader in bekery items operating a \nnetwork of company-owned and franchise-owned s\ntores in the Sri Lankan international markets. \n     BAKEHOUSE's is a company of exceptional people \non a mission to be the best bakery company \n\t  in the world.\n");
        jTextArea1.setBorder(null);
        loginPanel.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        lablelBurgerPic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lablelBurgerPic3.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMOD_PC\\Documents\\NetBeansProjects\\bakehousePhotos\\imageonline-co-transparentimage.png")); // NOI18N
        loginPanel.add(lablelBurgerPic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -80, 470, 600));

        lblFrontLayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrontLayer1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMOD_PC\\Documents\\NetBeansProjects\\bakehousePhotos\\downloadk.png")); // NOI18N
        loginPanel.add(lblFrontLayer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 250, 300));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("B_A_K_E  H_O_U_S_E");
        loginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 530, 40));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Secure Your Account  ");
        loginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 40, 530, 40));
        loginPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 230, 30));

        lblLoginPassword1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLoginPassword1.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginPassword1.setText("Confirm Password");
        loginPanel.add(lblLoginPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, 20));

        txtChangeNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChangeNewPassActionPerformed(evt);
            }
        });
        loginPanel.add(txtChangeNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 180, 30));

        btnChangeLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnChangeLogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnChangeLogin.setText("Login");
        btnChangeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeLoginActionPerformed(evt);
            }
        });
        loginPanel.add(btnChangeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 80, 60));
        loginPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 230, 10));

        lblLoginUserName2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLoginUserName2.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginUserName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginUserName2.setText("New User Name");
        loginPanel.add(lblLoginUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        txtChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChangeNameActionPerformed(evt);
            }
        });
        loginPanel.add(txtChangeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 180, 30));

        lblLoginPassword2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLoginPassword2.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginPassword2.setText("New Password");
        loginPanel.add(lblLoginPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 20));
        loginPanel.add(txtChangeConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 180, 30));

        lblFrontLayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrontLayer.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMOD_PC\\Documents\\NetBeansProjects\\bakehousePhotos\\downloadk.png")); // NOI18N
        loginPanel.add(lblFrontLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 500, 300));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Berlin Sans FB", 1, 16)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        loginPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 80, 60));

        lblLoginUserName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLoginUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginUserName.setText("User ID");
        loginPanel.add(lblLoginUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        loginPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 230, 20));

        btnLoginChange.setBackground(new java.awt.Color(255, 255, 255));
        btnLoginChange.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnLoginChange.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMOD_PC\\Documents\\NetBeansProjects\\bakehousePhotos\\icons8-settings-50.png")); // NOI18N
        btnLoginChange.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnLoginChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginChangeActionPerformed(evt);
            }
        });
        loginPanel.add(btnLoginChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 80, 60));

        lblLoginPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginPassword.setText("Password");
        loginPanel.add(lblLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 20));

        lblLoginUserName1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLoginUserName1.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginUserName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginUserName1.setText("User Name");
        loginPanel.add(lblLoginUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        loginPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 230, 20));

        txtLoginUserId.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtLoginUserId.setForeground(new java.awt.Color(153, 0, 0));
        txtLoginUserId.setToolTipText("");
        txtLoginUserId.setAlignmentX(5.0F);
        txtLoginUserId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txtLoginUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUserIdActionPerformed(evt);
            }
        });
        loginPanel.add(txtLoginUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, 30));

        txtLoginUserName.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtLoginUserName.setForeground(new java.awt.Color(153, 0, 0));
        txtLoginUserName.setToolTipText("");
        txtLoginUserName.setBorder(null);
        txtLoginUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginUserNameActionPerformed(evt);
            }
        });
        loginPanel.add(txtLoginUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 180, 30));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Say hi!  to Bake_House   ");
        loginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 40, 530, 40));

        txtLoginPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtLoginPassword.setForeground(new java.awt.Color(102, 0, 0));
        txtLoginPassword.setBorder(null);
        txtLoginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginPasswordActionPerformed(evt);
            }
        });
        loginPanel.add(txtLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMOD_PC\\Documents\\NetBeansProjects\\bakehousePhotos\\1.png")); // NOI18N
        loginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 240, 220));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMOD_PC\\Documents\\NetBeansProjects\\bakehousePhotos\\2.png")); // NOI18N
        loginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 320, 240));

        lablelRedTexture1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lablelRedTexture1.setIcon(new javax.swing.ImageIcon("C:\\Users\\AMOD_PC\\Documents\\NetBeansProjects\\bakehousePhotos\\downloadk.png")); // NOI18N
        loginPanel.add(lablelRedTexture1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 500, 300));

        jPanel2.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginChangeActionPerformed
        
        String uId=txtLoginUserId.getText();
         
        storeId=uId;
        String uName=txtLoginUserName.getText();
        String uPass=txtLoginPassword.getText();
        try{
            String sql="SELECT name,password FROM employee WHERE id='"+uId+"'";
            st = cn.prepareStatement(sql);
            rs=st.executeQuery();
            String Name=null;
            String Password=null;
            while(rs.next())
            {
                Name=rs.getString("name");
                Password=rs.getString("password");
            }
            if(Name.equals(uName) && Password.equals(uPass) )
            {
                 //hide burgur
                 lablelBurgerPic3.hide();
                //show front layer
                lblFrontLayer.show();
                //hide front layer
                lblFrontLayer1.hide();
                //hide conner text photos
                jLabel2.hide();
                jLabel1.hide();
                jTextArea1.show();
                //secure yur acc labale
                jLabel5.show();
                jLabel4.hide();
                jLabel6.show();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect details");
            }    
                 
                    
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Fill the Form");
        }

       
    }//GEN-LAST:event_btnLoginChangeActionPerformed
    // bring tht name to change password form
    String storeId=null;
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String uId=txtLoginUserId.getText();
        storeId=uId;
        String uName=txtLoginUserName.getText();
        String uPass=txtLoginPassword.getText();
        try{
            String sql="SELECT name,password FROM employee WHERE id='"+uId+"'";
            st = cn.prepareStatement(sql);
            rs=st.executeQuery();
            String Name=null;
            String Password=null;
            while(rs.next())
            {
                Name=rs.getString("name");
                Password=rs.getString("password");
            }
            if(Name.equals(uName) && Password.equals(uPass) )
            {
                 new home.SmartHome().setVisible(true);
                
                 this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect details");
            }    
                 
                    
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Fill the Form");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtLoginUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUserIdActionPerformed

    private void txtLoginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginPasswordActionPerformed

    private void txtLoginUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginUserNameActionPerformed

    private void txtChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChangeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChangeNameActionPerformed

    private void txtChangeNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChangeNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChangeNewPassActionPerformed

    private void btnChangeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeLoginActionPerformed
        
         String nameEmp=txtChangeName.getText();
         String changePassword=txtChangeNewPass.getText();
         String newPassword=txtChangeConfirmPass.getText();
         if(changePassword.equals(newPassword))
         {
             try
            {

                System.out.println("Stored VALUE: "+storeId);
                //String gg=storeId;
                String sql2="Update employee set name='"+nameEmp+"', password='"+newPassword+"' where id= '"+txtLoginUserId.getText()+"' ";
              //  String sql2="Update employee set name='"+nameEmp+"', contactNumber='"+contactNum+"', email='"+email+"',address='"+address+"', password='"+password+"',type='"+type+"' where id='"+id+"' ";

                st = cn.prepareStatement(sql2);
                st.execute();

                JOptionPane.showMessageDialog(null,"UPDATED");
                 new home.SmartHome().setVisible(true);
                
                 this.setVisible(false);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error:UPDATE");
            } 
         }
         else
         {
             JOptionPane.showMessageDialog(null,"Not Math your Password");
         }
       
    }//GEN-LAST:event_btnChangeLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lablelBurgerPic3;
    private javax.swing.JLabel lablelRedTexture1;
    private javax.swing.JLabel lblFrontLayer;
    private javax.swing.JLabel lblFrontLayer1;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginPassword1;
    private javax.swing.JLabel lblLoginPassword2;
    private javax.swing.JLabel lblLoginUserName;
    private javax.swing.JLabel lblLoginUserName1;
    private javax.swing.JLabel lblLoginUserName2;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField txtChangeConfirmPass;
    private javax.swing.JTextField txtChangeName;
    private javax.swing.JTextField txtChangeNewPass;
    private javax.swing.JPasswordField txtLoginPassword;
    private javax.swing.JTextField txtLoginUserId;
    private javax.swing.JTextField txtLoginUserName;
    // End of variables declaration//GEN-END:variables
}
